config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  root to: 'inquiry#index'
  get 'inquiry/index'
  post 'inquiry/confirm'
  post 'inquiry/thanks'

  resources :users, only: [:show, :edit, :update, :index] do
    get 'users/favorite' => 'users#favorite'
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'search' => 'posts#search'
  get 'posts/hashtag/:name' => 'posts#hashtag'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :notifications, only: :index

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # follower:フォローするユーザー, followed:フォローされるユーザー
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  # フォロー機能を作成・保存・削除する
  def create
    @user = User.find(params[:user_id])
    current_user.follow(params[:user_id])
    @user.create_notification_follow!(current_user)
    # redirect_to request.referer
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(params[:user_id])
    # redirect_to request.referer
  end


  # フォロー・フォロワー一覧を表示する
  def followings # フォローしているユーザー
    @user = User.find(params[:user_id])
    @users = @user.followings
  end

  def followers # フォローされているユーザー
    @user = User.find(params[:user_id])
    @users = @user.followers
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% if user != current_user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, remote: true, class: 'text-dark', id:'nofollow' %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, id:'yesfollow' %>
  <% end %>
<% end %>

app/views/relationships/create.js.erb
$("#follow_").html("<%= j(render("relationships/follow")) %>");
$("#follow_count").html("<%= @user.followings.count %> フォロー");
$("#follower_count").html("<%= @user.followers.count %> フォロワー");

app/views/relationships/destroy.js.erb
$("#follow_").html("<%= j(render("relationships/follow")) %>");
$("#follow_count").html("<%= @user.followings.count %> フォロー");
$("#follower_count").html("<%= @user.followers.count %> フォロワー");

app/views/relationships/followers.html.erb
<main class="bg-white shadow-sm">
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <%= render 'users/userinfo', user: @user %>
      <div class="col-md-9 ">
        </br>
        <h5>
          <i class="fas fa-user"></i>
          <strong>フォロワー</strong>
        </h5>
        <table class='table table-inverse'>
          <% if @users.exists? %>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <% if user.profile_image.attached? %>
                    <%= image_tag user.profile_image, class:"circle5"; %>
                  <% else %>
                    <%= image_tag('no_image.jpg', class:"circle5") %>
                  <% end %>
                </td>
                <td>
                  <%= link_to user.name, user_path(user) %>
                </td>
                <td>
                  フォロー数: <%= user.followings.count %>
                </td>
                <td>
                  フォロワー数: <%= user.followers.count %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <div class="card-deck-container col-md-9">
              ユーザーはいません。
            </div>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/relationships/followings.html.erb
<main class="bg-white shadow-sm">
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <%= render 'users/userinfo', user: @user %>
      <div class="col-md-9 ">
        </br>
        <h5>
          <i class="fas fa-user"></i>
          <strong>フォロー</strong>
        </h5>
        <table class='table table-inverse'>
          <% if @users.exists? %>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <% if user.profile_image.attached? %>
                    <%= image_tag user.profile_image, class:"circle5"; %>
                  <% else %>
                    <%= image_tag('no_image.jpg', class:"circle5") %>
                  <% end %>
                </td>
                <td>
                  <%= link_to user.name, user_path(user) %>
                </td>
                <td>
                  フォロー数: <%= user.followings.count %>
                </td>
                <td>
                  フォロワー数: <%= user.followers.count %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <div class="card-deck-container col-md-9">
              ユーザーはいません。
            </div>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>