config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  root to: 'inquiry#index'
  get 'inquiry/index'
  post 'inquiry/confirm'
  post 'inquiry/thanks'

  resources :users, only: [:show, :edit, :update, :index] do
    get 'users/favorite' => 'users#favorite'
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'search' => 'posts#search'
  get 'posts/hashtag/:name' => 'posts#hashtag'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :notifications, only: :index

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_rooms
  has_many :chats

  # follower_id:フォローするユーザーのid, followed_id:フォローされるユーザーのid
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  # visitor_id : 通知を送ったユーザーのid  visited_id : 通知を送られたユーザーのid
  # active_notificationsは自分からの通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # passive_notificationsは相手からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 1, maximum: 10 }
  validates :introduction, length: { maximum: 50 }
  has_one_attached :profile_image
  validate :profile_image_type


  # フォロー・フォロワー
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end


  # 通知機能 フォロー
  def create_notification_follow!(current_user)
    # 既に「フォロー」されているかを検索
    notifications = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    # フォローがされていなかったら、通知レコードを作成
    if notifications.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end


  private

  def profile_image_type
    if profile_image.attached?
      if !profile_image.blob.content_type.in?(%('profile_image/jpeg profile_image/png'))
        profile_image.purge # Rails6では、この1行は必要ない
        errors.add(:profile_image, 'はJPEGまたはPNG形式を選択してアップロードしてください')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = "保存しました。"
    else
      render :edit
    end
  end

  def destroy
  end

  def favorite
    @user = User.find(params[:user_id])
    favorites = Favorite.where(user_id: current_user.id).pluck(:post_id)
    @favorite_list = Post.find(favorites)
    @favorite_lists = Kaminari.paginate_array(@favorite_list).page(params[:page])
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error_windows.html.erb
<div id = "error_explanation" style="background-color: #FFB6C1;" class="shadow-sm">
  <% if post.errors.any? %>
    <div class="ml-4 mt-3">
      <%= post.errors.count %> 件のエラーが発生しました。
    </div>
    <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/users/_flash_notice.html.erb
<div id = "error_explanation" style="background-color: #EEFFFF;" class="shadow-sm">
  <% if flash[:notice] %>
    <div class="ml-4 my-2">
      <%= flash[:notice] %>
    </div>
  <% end %>
</div>

app/views/users/_loadimage.html.erb
<script>
  function loadImage(obj)
  {
    // 選択した画像を読み込む
    var allPreview = document.getElementById('profile_image');
    // <p>を作成する
    var newPreview = document.createElement("p");
    // post_imageの中の<p>を取り除く
    allPreview.querySelector("p").remove();
    // <p>を<p id="preview"></p>に設定
    newPreview.setAttribute("id","preview");
    // <p id="preview"></p>を<div id="post_image">の中の最初の要素として設定
    allPreview.insertBefore(newPreview, allPreview.firstChild);
    // viewの方でnone(非表示)にしている部分を表示に変更
    document.getElementById("profile_image").style.display = "";
    for (i = 0; i < obj.files.length; i++) {
        var fileReader = new FileReader();
        fileReader.onload = (function (e) {
            var img = new Image();
            img.src = e.target.result;
            img.classList.add('userprv')
            document.getElementById('preview').appendChild(img);
        });
      fileReader.readAsDataURL(obj.files[i]);
    }
  }
</script>

app/views/users/_userinfo.html.erb
<div class='col-md-3 text-center'>
  <table class="mx-auto text-break">
    </br>
    <tr>
      <%= link_to user_path(user.id) do %>
        <% if user.profile_image.attached? %>
          <%= image_tag user.profile_image, class: "circle" %>
        <% else %>
          <%= image_tag('no_image.jpg', class: "circle") %>
        <% end %>
      <% end %>
    </tr>
    <tr>
      <th></th>
    </tr>
    <tr>
      <th><h3><%= user.name %></h3></th>
    </tr>
  </table>
  <div>
    <strong>
  	  <span id="follow_">
  	    <%= render 'relationships/follow', user: user %>
  	  </span></br>
      <%= link_to user_followings_path(user.id) do %>
        <span id="follow_count"><%= user.followings.count %> フォロー</span>
      <% end %>
    </strong>
  </div>
  <div>
    <strong>
      <%= link_to user_followers_path(user.id) do %>
        <span id="follower_count"><%= user.followers.count %> フォロワー</span>
      <% end %>
      <% if current_user != user %>
        <%= link_to ' chatを始める', chat_path(user.id), class: 'fas fa-comment-dots' %>
      <% end %>
    </strong>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'users/error_windows', post: @user %>
<main class="bg-white shadow-sm">
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <%= render 'users/userinfo', user: @user %>
      <div class='col-md-9 pb-4'>
        </br>
        <strong>
          <%= form_with model: @user, local: true do |f| %>
            <div class="page-header">
              <h5>
                <i class="fas fa-pencil-alt"></i>
                <strong>プロフィール編集</strong>
              </h5>
            </div></br>
            <div class="form-group">
              <label for="user_name">名前
                <span class="text-black-50">（10文字以内）</span>
              </label></br>
              <%= f.text_field :name, autofocus: true, class:"form-control col-5 shadow-sm" %>
            </div></br>
            <div class="form-group">
              <div class="field">
                <%= f.label :profile_image, "画像" %><span class="must"></span>
              <span class="text-black-50">（必須）</span>
              </div>
              <!--javascriptとの関連付けを行う記述-->
              <%= f.file_field :profile_image, class: "push", onchange: "loadImage(this);" %>
            </div></br>
              <!--選択した画像をプレビュー表示する記述-->
            <div id="profile_image" style="display: none;">
              <p id="preview"></p>
            </div>
            <div class="form-group">
              <label for="user_introduction">自己紹介
                <span class="text-black-50">（50文字以内）</span>
              </label></br>
              <%= f.text_area :introduction, autofocus: true, class:"form-control col-8 shadow-sm" %>
            </div></br>
            <div class="form-group">
              <%= f.submit "保存する", class:"btn btn-outline-info" %>
            </div>
          <% end %></br></br></br>
          
            <h5>
              <strong>現在のプロフィール</strong></br></br>
            </h5>
              <div class="card col-10 shadow-sm">
              <p class="mt-3 mx-4">プロフィール画像</p>
              <% if @user.profile_image.attached? %>
                <%= image_tag @user.profile_image.variant(resize:'250x250'), class:"circle2 mx-3 mt-1" %>
              <% else %>
                <%= image_tag('no_image.jpg', size:'250x250', class:"circle2 mx-3 mt-3") %>
              <% end %>
              </br></br><p class="mx-4">名前</p>
              <p class="mx-4"><%= @user.name %></p></br>
              <p class="mx-4">自己紹介</p>
              <p class="mx-4"><%= @user.introduction %></p>
              </div>
            
          <%= render "loadimage" %>
        </strong>
      </div>
    </div>
  </div>
</main>

app/views/users/favorite.html.erb
<main class="bg-white shadow-sm">
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <%= render 'users/userinfo', user: current_user %>
      <div class="card-deck-container col-md-9">
        </br>
        <h5>
          <i class="fas fa-heart"></i>
          <strong>お気に入り一覧</strong>
        </h5>
        <%= render 'posts/posts_index', post: @favorite_lists %>
        <%= paginate @favorite_lists %>
      </div>
  </div>
</main>

app/views/users/show.html.erb
<%= render 'users/flash_notice' %>
<main class="bg-white shadow-sm">
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <%= render 'users/userinfo', user: @user %>
      <div class='col-md-9'>
        </br>
        <h5>
          <i class="fas fa-address-card"></i>
          <strong>ユーザー情報</strong>
        </h5>
        <div class="background col-md-11 pb-2">
          </br>
          <div class="col-6 offset-md-1 mb-2 embed-responsive">
            <% if @user.profile_image.attached? %>
              <%= image_tag @user.profile_image, class:"circle2" %>
            <% else %>
              <%= image_tag('no_image.jpg', class:"circle2") %>
            <% end %>
          </div>
          <div class="col-8 offset-md-1">
            <strong>ユーザーネーム</strong></br>
            <h2><%= @user.name %></h2></br>
            <strong>自己紹介</strong></br>
            <h6>
              <% if @user.introduction.present? %>
                <%= safe_join(@user.introduction.split("\n"),tag(:br)) %>
              <% else %>
                登録されていません。
              <% end %>
            </h6>
          </div>
        </div>
        <div class="col-md-11 my-3">
          <% if @user == current_user %>
            <%= link_to "プロフィールを編集する", edit_user_path, class:"btn btn-outline-info btn-sm col-md-7 float-right" %></br>
          <% end %>
        </div>
        <div class="card-deck-container col-md-14">
          </br>
          <h4><%= @user.name %>さんの投稿</h4>
          <div class="row">
            <% if @posts.present? %>
              <% @posts.each do |post| %>
                <div class="card col-5 mx-3 mb-4 embed-responsive shadow-sm">
                  <% if post.post_image.attached? %>
                    <%= link_to post_path(post.id) do %>
                      <%= image_tag post.post_image, class:"card-img-top"; %>
                    <% end %>
                  <% else %>
                    <%= image_tag('no_image.jpg') %>
                  <% end %>
                  <div class="card-body">
                    <div class="row">
                      <div class="col-md-2">
                        <% if post.user.profile_image.attached? %>
                          <%= image_tag @user.profile_image, class:"mt-3 circle3"; %>
                        <% else %>
                          <%= image_tag('no_image.jpg', class:"mt-3 circle3") %>
                        <% end %>
                      </div>
                      <div class="col-md-9 offset-md-1 col-xl-7 offset-xl-3">
                        <p class="card-title">
                          <p><%= post.created_at.strftime('%Y/%m/%d') %></p>
                          <strong>
                            <i class="far fa-flag"></i>
                            <span> <%= post.title %></span>
                          </strong>
                        </p>
                        <span><i class="fas fa-user"></i>  <%= post.user.name %></span></br>
                        <span><%= post.favorites.count %> いいね ｜ </span>
                        <span><%= post.post_comments.count %> コメント</span></br></br>
                        <% if @user == current_user %>
                          <span>
                            <%= link_to "編集", edit_post_path(post), class:"btn btn-outline-info btn-sm" %>
                          　<%= link_to "削除", post_path(post), method: :delete, class:"btn btn-outline-danger btn-sm", "data-confirm" => "本当に削除しますか？" %>
                          </span>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div class="card-deck-container col-md-9">
               まだ投稿がありません。
              </div>
            <% end %>
          </div>
          <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>
</main>