config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  root to: 'inquiry#index'
  get 'inquiry/index'
  post 'inquiry/confirm'
  post 'inquiry/thanks'

  resources :users, only: [:show, :edit, :update, :index] do
    get 'users/favorite' => 'users#favorite'
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'search' => 'posts#search'
  get 'posts/hashtag/:name' => 'posts#hashtag'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :notifications, only: :index

end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))    
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/inquiry/confirm.html.erb
<main class="bg-white shadow-sm">
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <%= render 'users/userinfo', user: current_user %>
      <div class='col-md-9 mb-3'>
        </br>
        <strong>
          <h4></h4>
          <div class="page-header">
            <h5>
              <i class="fas fa-question-circle"></i>
              <strong>入力内容をご確認ください</strong>
            </h5>
          </div>

          <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
            <table class="table">
              <tr>
                <th>名前</th>
                <td>
                  <%= f.hidden_field :name %>
                  <%= @inquiry.name %>
                </td>
              </tr>
              <tr>
                <th>メールアドレス</th>
                <td>
                  <%= f.hidden_field :email %>
                  <%= @inquiry.email %>
                </td>
              </tr>
              <tr>
                <th>お問い合わせ内容</th>
                <td>
                  <%= f.hidden_field :message %>
                  <%= simple_format(@inquiry.message) %>
                </td>
              </tr>
            </table>
            <div class="col-4 offset-9">
            <%= f.submit '送信', class:"btn btn-outline-info" %>
            <% end %>
            </div>
          </div>
        </strong>
      </div>
    </div>
  </div>
</main>

app/views/inquiry/index.html.erb
<main class="bg-white shadow-sm">
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <%= render 'users/userinfo', user: current_user %>
      <div class='col-md-9 mb-3'>
        </br>
        <strong>
          <h4></h4>
          <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
          <div class="page-header">
            <h5>
              <i class="fas fa-question-circle"></i>
              <strong>問い合わせ</strong>
            </h5>
          </div>
          <% if @inquiry.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <strong>入力内容にエラーがあります</strong>
              <ul>
                <% @inquiry.errors.each do |attr, msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <table class="table col-md-11">
            <tr>
              <th>
                名前
                <span class="text-black-50">（必須）</span>
              </th>
              <td><%= f.text_field :name, class:"form-control col-5 shadow-sm" %></td>
            </tr>
            <tr>
              <th>
                メールアドレス
                <span class="text-black-50">（必須）</span>
              </th>
              <td><%= f.text_field :email, class:"form-control col-8 shadow-sm" %></td>
            </tr>
            <tr>
              <th>お問い合わせ内容</th>
              <td><%= f.text_area :message, class:"form-control col-11 shadow-sm" %></td>
            </tr>
          </table>
          <div class="col-4 offset-9">
            <%= f.submit '確認', class:"btn btn-outline-info" %>
            <% end %>
          </div>
        </strong>
      </div>
    </div>
  </div>
</main>

app/views/inquiry/thanks.html.erb
<main class="bg-white shadow-sm">
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <%= render 'users/userinfo', user: current_user %>
      <div class='col-md-9 mb-3'>
        </br>
        <strong>
          <h4></h4>
          <div class="page-header">
            <h5>
              <i class="fas fa-question-circle"></i>
              <strong>お問い合わせ</strong>
            </h5>
            <p>
              お問い合わせいただきありがとうございました。
            </p>
          </div>
        </strong>
      </div>
    </div>
  </div>
</main>