config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  root to: 'inquiry#index'
  get 'inquiry/index'
  post 'inquiry/confirm'
  post 'inquiry/thanks'

  resources :users, only: [:show, :edit, :update, :index] do
    get 'users/favorite' => 'users#favorite'
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'search' => 'posts#search'
  get 'posts/hashtag/:name' => 'posts#hashtag'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :notifications, only: :index

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg-light">

  <head>
    <title>Nanakamado</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/swiper@4.5.1/dist/css/swiper.min.css"/>
    <script src="//cdn.jsdelivr.net/npm/swiper@4.5.1/dist/js/swiper.min.js"></script>
    <%= favicon_link_tag "logo.png" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light d-flex flex-column col-md-8 offset-md-2">
    <header class="bg-white shadow-sm my-3">
      <div class="col-xs-6 col-md-9 site-logo">
        <nav class="navbar navbar-expand-lg col-lg-12 navbar-light">
		  	  </br>
		  	  <div class="mr-2">
		  	    <%= link_to root_path do %>
              <%= image_tag('logo.png', size:'90x90') %>
            <% end %>
          </div>
          <p class="mt-4">
            <span>北欧雑貨やおうち時間を語らうサイト</span></br>
            <span>
		  	      <%= link_to root_path do %>
                <%= image_tag('logoname.png', size:'220x40') %>
              <% end %>
            </span>
          </p>
        </nav>
      </div>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <% if user_signed_in? %>
              <ul class="navbar-nav w-100 nav-justified font-type">
                <li class="nav-item">
                  <%= link_to ' About', home_about_path, class: 'fas fa-leaf nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to ' 新規投稿', new_post_path, class: 'fas fa-pencil-alt nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to ' 投稿一覧', posts_path, class: 'fas fa-book-open nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to ' お気に入り', user_users_favorite_path(current_user.id), class: 'fas fa-heart nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <% if unchecked_notifications.any? %>
                    <span class="fa-stack">
                      <%= link_to ' お知らせ', notifications_path, class: 'fas fa-bell  nav-link text-dark' %>
                      <i class="fas fa-circle n-circle "></i>
                    </span>
                  <% else %>
                      <%= link_to ' お知らせ', notifications_path, class: 'fas fa-bell  nav-link text-dark' %>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to ' マイページ', user_path(current_user.id), class: 'fas fa-address-card nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to " ログアウト", destroy_user_session_path, method: :delete, class: 'fas fa-door-open nav-link text-dark' %>
                </li>
              </ul>
            <% else %>
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <%= link_to ' About', home_about_path, class: 'fas fa-leaf nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to " 新規登録", new_user_registration_path, class: 'fas fa-user-plus nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to " ログイン", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-dark' %>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <div>

    </div>
    <%= yield %>
    <footer class="bg-danger text-light pt-4 pb-3 mt-3 mb-3 shadow-sm">
      <div class="container text-center">
        <p><%= link_to ' お問い合わせ', inquiry_index_path, class: 'fas fa-question-circle text-white' %></p>
        <p>Copyright 2021&copy; nanakamado. All Rights Reserved.</p>
      </div>
    </footer>
  </body>

</html>